/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import elementos.GameObject;
import elementos.Player;
import elementos.World;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class GameView extends javax.swing.JFrame {

    private World world;
    private int width;
    private int height;
    /**
     * Creates new form GameView
     */
    public GameView(int width, int height, String name , World world) {
        initComponents();
        this.width = width;
        this.world = world;
        this.height = height;
        inicializarFrame(name);
        crearVistaMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_W) world.keyPressed(1, true);
        if(key == KeyEvent.VK_S) world.keyPressed(2, true);
        if(key == KeyEvent.VK_A) world.keyPressed(3, true);
        if(key == KeyEvent.VK_D) world.keyPressed(4, true);
        
//        if(key == KeyEvent.VK_ESCAPE){
//            ventana.getFrame().setVisible(false);
//            ventana.crearVistaMenu();
//        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        int key = evt.getKeyCode();
        
        if(key == KeyEvent.VK_W) world.keyPressed(1, false);
        if(key == KeyEvent.VK_S) world.keyPressed(2, false);
        if(key == KeyEvent.VK_A) world.keyPressed(3, false);
        if(key == KeyEvent.VK_D) world.keyPressed(4, false);
    }//GEN-LAST:event_formKeyReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    

    public void inicializarFrame(String name){
        setName(name);
        setPreferredSize(new Dimension(width, height));
        setMaximumSize(new Dimension(width, height));
        setMinimumSize(new Dimension(width, height));
        add(world);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(false);
    }
    
    public void decidirBotonesMenu(MenuView menuView) {
        switch(menuView.getEstado()) {
            case 1:
                setVisible(true);
                LoadView loadView = new LoadView(this, false);
            break;
            case 2:
                InstructionsView instructionsView = new InstructionsView(this, true);
                decidirBotonesInstrucciones(instructionsView);
            break;
            case 3:
                System.exit(0);
            break;
        }
    }
    
    public void decidirBotonesInstrucciones(InstructionsView instructionsView) {
        switch(instructionsView.getEstado()) {
            case 1:
                crearVistaMenu();
            break;
        }
    }
    
    public void crearVistaMenu() {
       MenuView menuView = new MenuView(this, true);
       decidirBotonesMenu(menuView);
    }

    public void setMundo(World world) {
        this.world = world;
    }

    public JFrame getFrame() {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
