/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author dgutierrezd
 */
public class MenuView extends javax.swing.JDialog {

    Ventana ventana;
    
    /**
     * Accion hechas por el usuario en esta vista.
     */
    int estado;
    
    /**
     * Creates new form MenuView
     */
    public MenuView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setVisible(true);
        setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPlay = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bInstructions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bPlay.setForeground(new java.awt.Color(145, 150, 153));
        bPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlayNow.png"))); // NOI18N
        bPlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bPlay.setBorderPainted(false);
        bPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPlay.setLabel("");
        bPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayActionPerformed(evt);
            }
        });
        getContentPane().add(bPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, 50));

        bExit.setForeground(new java.awt.Color(145, 150, 153));
        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        bExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExit.setPreferredSize(new java.awt.Dimension(54, 44));
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        bInstructions.setForeground(new java.awt.Color(145, 150, 153));
        bInstructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Instructions.png"))); // NOI18N
        bInstructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bInstructions.setPreferredSize(new java.awt.Dimension(128, 44));
        getContentPane().add(bInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AvengersIcon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaptainAmericaShield (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IronMan (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AvengersPixel.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        estado = 3;
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayActionPerformed
        estado = 1;
        //        ventana.decidirBotonesMenu(estado);
        dispose();
    }//GEN-LAST:event_bPlayActionPerformed

    public int getEstado() {
        return estado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bInstructions;
    private javax.swing.JButton bPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
